### ISSUE TITLE
Mushroom top chunky face room issue

### ISSUE THREAD

**Issue by KaziiTheAvali** [Electric-Fortune/bananatracker#2]
currently its marked as unable to reach chunky face room with this item set however you can only needing to beable to get to the top of the mushroom with chunky, have pineapple launcher, and have default slam (with random level order)
![image](https://github.com/Electric-Fortune/bananatracker/assets/87594664/df468e7c-d74d-4a8d-b48b-18c8f4712c0e)
this is mostlikely due to how the randomizer levels progressive switches making the earlyer stages have a lower level switch then the higher stages
![image](https://github.com/Electric-Fortune/bananatracker/assets/87594664/e5e3f1dc-49e9-4430-ae5f-b5e5ea7ec228)

**Comment by KaziiTheAvali** [comment]
the switch progression is first 4 is green next 2 is blue and last 1 is red acording to the DK64 randomizer discord. this is not including the ship. that is always green

**Comment by Lebon14** [comment]
I know of one switch - the Galleon Diddy Ship Switch - that cannot be changed color no matter what level Galleon is because it's part of the boat model.

However, I'm not sure about the Chunky Top of Mushroom Puzzle Door... if it's green all the time and that hasn't changed in version 3, then, I imagine there's a reason why it can't be changed.

Anyway, the map tracker is creeping up slowly towards its first year without any update... :(

**Comment by Electric-Fortune** [comment]
This should now be fixed with v1.4.0.
